/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SideNote
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/commentManager.ts
var CommentManager = class {
  constructor(comments) {
    this.MIN_TEXT_LENGTH = 3;
    this.comments = comments;
  }
  generateHash(text) {
    try {
      const nodeCrypto = require("crypto");
      return nodeCrypto.createHash("sha256").update(text).digest("hex");
    } catch (e) {
      let hash = 0;
      for (let i = 0; i < text.length; i++) {
        const char = text.charCodeAt(i);
        hash = (hash << 5) - hash + char;
        hash = hash & hash;
      }
      return Math.abs(hash).toString(16);
    }
  }
  getCommentsForFile(filePath) {
    return this.comments.filter((c) => c.filePath === filePath);
  }
  addComment(newComment) {
    if (!newComment.selectedTextHash) {
      newComment.selectedTextHash = this.generateHash(newComment.selectedText);
    }
    this.comments.push(newComment);
  }
  editComment(id, newCommentText) {
    const comment = this.comments.find((c) => c.id === id);
    if (comment) {
      comment.comment = newCommentText;
    }
  }
  deleteComment(id) {
    const index = this.comments.findIndex((c) => c.id === id);
    if (index > -1) {
      this.comments.splice(index, 1);
    }
  }
  resolveComment(id) {
    const comment = this.comments.find((c) => c.id === id);
    if (comment) {
      comment.resolved = true;
      comment.resolvedAt = Date.now();
    }
  }
  unresolveComment(id) {
    const comment = this.comments.find((c) => c.id === id);
    if (comment) {
      comment.resolved = false;
      comment.resolvedAt = null;
    }
  }
  deleteOrphanedComments() {
    const before = this.comments.length;
    for (let i = this.comments.length - 1; i >= 0; i--) {
      if (this.comments[i].isOrphaned) {
        this.comments.splice(i, 1);
      }
    }
    return before - this.comments.length;
  }
  getOrphanedComments() {
    return this.comments.filter((c) => c.isOrphaned);
  }
  getOrphanedCommentCount() {
    return this.getOrphanedComments().length;
  }
  renameFile(oldPath, newPath) {
    this.comments.forEach((c) => {
      if (c.filePath === oldPath) {
        c.filePath = newPath;
      }
    });
  }
  updateComments(newComments) {
    this.comments = newComments;
  }
  getComments() {
    return this.comments;
  }
  // Weight line distance more heavily than char distance so nearby lines rank first
  calculateDistance(line1, char1, line2, char2) {
    return Math.abs(line1 - line2) * 1e3 + Math.abs(char1 - char2);
  }
  findTextPositionWithHashVerification(fileContent, selectedText, selectedTextHash, hintStartLine, hintStartChar, hintEndLine) {
    if (!selectedText || selectedText.length < this.MIN_TEXT_LENGTH) return null;
    const lines = fileContent.split("\n");
    const escapedText = selectedText.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(escapedText, "g");
    const startLine = Math.max(0, hintStartLine - 10);
    const endLine = Math.min(lines.length, hintEndLine + 10);
    const candidates = [];
    for (let lineNum = startLine; lineNum < endLine; lineNum++) {
      regex.lastIndex = 0;
      let match;
      while ((match = regex.exec(lines[lineNum])) !== null) {
        const foundText = lines[lineNum].substring(match.index, match.index + selectedText.length);
        if (this.generateHash(foundText) === selectedTextHash) {
          candidates.push({
            line: lineNum,
            startChar: match.index,
            endChar: match.index + selectedText.length,
            distance: this.calculateDistance(lineNum, match.index, hintStartLine, hintStartChar)
          });
        }
      }
    }
    if (candidates.length === 0) return null;
    candidates.sort((a, b) => a.distance - b.distance);
    const { line, startChar, endChar } = candidates[0];
    return { line, startChar, endChar };
  }
  findTextByHashOptimized(fileContent, selectedTextHash, originalTextLength, hintStartLine, hintStartChar) {
    const lines = fileContent.split("\n");
    const candidates = [];
    for (let lineNum = 0; lineNum < lines.length; lineNum++) {
      const line2 = lines[lineNum];
      const lengths = /* @__PURE__ */ new Set([originalTextLength]);
      const minLen = Math.max(this.MIN_TEXT_LENGTH, Math.floor(originalTextLength * 0.8));
      const maxLen = Math.min(line2.length, Math.ceil(originalTextLength * 1.2));
      for (let l = minLen; l <= maxLen; l++) lengths.add(l);
      for (const length of lengths) {
        if (line2.length < length) continue;
        for (let startChar2 = 0; startChar2 <= line2.length - length; startChar2++) {
          const candidate = line2.substring(startChar2, startChar2 + length);
          if (this.generateHash(candidate) === selectedTextHash) {
            const distance = hintStartLine !== void 0 && hintStartChar !== void 0 ? this.calculateDistance(lineNum, startChar2, hintStartLine, hintStartChar) : 0;
            candidates.push({ line: lineNum, startChar: startChar2, endChar: startChar2 + length, text: candidate, distance });
          }
        }
      }
    }
    if (candidates.length === 0) return null;
    candidates.sort((a, b) => a.distance - b.distance);
    const { line, startChar, endChar, text } = candidates[0];
    return { line, startChar, endChar, text };
  }
  findTextPosition(fileContent, selectedText, hintStartLine, hintEndLine, hintStartChar) {
    if (!selectedText || selectedText.length < this.MIN_TEXT_LENGTH) return null;
    const lines = fileContent.split("\n");
    const escapedText = selectedText.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(escapedText, "g");
    const searchRange = (startLine, endLine) => {
      const found = [];
      for (let lineNum = startLine; lineNum < endLine; lineNum++) {
        regex.lastIndex = 0;
        let match;
        while ((match = regex.exec(lines[lineNum])) !== null) {
          const distance = hintStartLine !== void 0 && hintStartChar !== void 0 ? this.calculateDistance(lineNum, match.index, hintStartLine, hintStartChar) : 0;
          found.push({ line: lineNum, startChar: match.index, endChar: match.index + selectedText.length, distance });
        }
      }
      return found;
    };
    const rangeStart = hintStartLine !== void 0 ? Math.max(0, hintStartLine - 10) : 0;
    const rangeEnd = hintEndLine !== void 0 ? Math.min(lines.length, hintEndLine + 10) : lines.length;
    let candidates = searchRange(rangeStart, rangeEnd);
    if (candidates.length === 0 && hintStartLine !== void 0) {
      candidates = searchRange(0, lines.length);
    }
    if (candidates.length === 0) return null;
    candidates.sort((a, b) => a.distance - b.distance);
    const { line, startChar, endChar } = candidates[0];
    return { line, startChar, endChar };
  }
  updateCommentCoordinatesForFile(fileContent, filePath) {
    const fileComments = this.comments.filter((c) => c.filePath === filePath);
    const lines = fileContent.split("\n");
    for (const comment of fileComments) {
      if (comment.isOrphaned) {
        if (this.textAtCoordsMatches(lines, comment)) {
          comment.isOrphaned = false;
        }
        continue;
      }
      const newPosition = this.resolveCommentPosition(fileContent, comment);
      if (newPosition) {
        comment.startLine = newPosition.line;
        comment.startChar = newPosition.startChar;
        comment.endLine = newPosition.line;
        comment.endChar = newPosition.endChar;
        comment.isOrphaned = false;
      } else {
        comment.isOrphaned = true;
      }
    }
  }
  textAtCoordsMatches(lines, comment) {
    if (comment.startLine < 0 || comment.startLine >= lines.length) return false;
    const line = lines[comment.startLine];
    if (comment.startChar < 0 || comment.endChar > line.length || comment.startChar > comment.endChar) return false;
    return line.slice(comment.startChar, comment.endChar) === comment.selectedText;
  }
  resolveCommentPosition(fileContent, comment) {
    if (comment.selectedTextHash) {
      const byHash = this.findTextPositionWithHashVerification(
        fileContent,
        comment.selectedText,
        comment.selectedTextHash,
        comment.startLine,
        comment.startChar,
        comment.endLine
      );
      if (byHash) return byHash;
      return null;
    }
    return this.findTextPosition(
      fileContent,
      comment.selectedText,
      comment.startLine,
      comment.endLine,
      comment.startChar
    );
  }
};

// src/core/markdownCommentBlocks.ts
function buildMarkdownBlock(excerpt, body, commentId) {
  const safeExcerpt = excerpt || "(no excerpt)";
  return `## ${safeExcerpt}
<!-- side-note:${commentId} -->
${body}

---`;
}

// src/SideNoteView.ts
var import_obsidian3 = require("obsidian");

// src/CommentModal.ts
var import_obsidian = require("obsidian");

// src/core/modalActionBindings.ts
function bindModalActionHandlers(args) {
  const now = args.now || (() => Date.now());
  const handleCancel = () => {
    if (args.submitGuard.isSubmitting()) {
      return;
    }
    args.onCancelTriggered();
  };
  const handleSubmit = async () => {
    var _a;
    const triggerResult = args.submitGuard.tryConsumeTrigger(now());
    if (!triggerResult.accepted) {
      (_a = args.onDebounceSuppressed) == null ? void 0 : _a.call(args, triggerResult.deltaMs);
      return;
    }
    await args.onSubmitTriggered();
  };
  args.cancelButton.addEventListener("click", () => {
    handleCancel();
  }, false);
  args.cancelButton.addEventListener("touchstart", (event) => {
    event.preventDefault();
  }, false);
  args.cancelButton.addEventListener("touchend", (event) => {
    event.preventDefault();
    event.stopPropagation();
    handleCancel();
  }, false);
  args.submitButton.addEventListener("click", () => {
    void handleSubmit();
  }, false);
  args.submitButton.addEventListener("touchstart", (event) => {
    event.preventDefault();
  }, false);
  args.submitButton.addEventListener("touchend", (event) => {
    event.preventDefault();
    event.stopPropagation();
    void handleSubmit();
  }, false);
}

// src/core/submitExecutionGuard.ts
var SubmitExecutionGuard = class {
  constructor(debounceMs) {
    this.submitting = false;
    this.lastTriggerAt = 0;
    this.debounceMs = debounceMs;
  }
  tryConsumeTrigger(now) {
    const deltaMs = now - this.lastTriggerAt;
    if (this.lastTriggerAt !== 0 && deltaMs < this.debounceMs) {
      return { accepted: false, deltaMs };
    }
    this.lastTriggerAt = now;
    return { accepted: true, deltaMs };
  }
  tryStartSubmit() {
    if (this.submitting) {
      return false;
    }
    this.submitting = true;
    return true;
  }
  finishSubmit() {
    this.submitting = false;
  }
  isSubmitting() {
    return this.submitting;
  }
  reset() {
    this.submitting = false;
    this.lastTriggerAt = 0;
  }
};

// src/CommentModal.ts
var CommentModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit, initialComment = "") {
    super(app);
    this.comment = "";
    this.textareaEl = null;
    this.submitButtonEl = null;
    this.cancelButtonEl = null;
    this.submitGuard = new SubmitExecutionGuard(400);
    this.onSubmit = onSubmit;
    this.initialComment = initialComment;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("sidenote-comment-modal");
    contentEl.createEl("h2", { text: this.initialComment ? "Edit comment" : "Add comment" });
    const inputContainer = contentEl.createDiv("sidenote-comment-input-container");
    const input = inputContainer.createEl("textarea");
    input.placeholder = "Enter your comment...";
    input.value = this.initialComment;
    input.classList.add("sidenote-textarea");
    this.textareaEl = input;
    input.addEventListener("keydown", (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
        e.preventDefault();
        void this.submitComment();
      }
      if (e.key === "Escape") {
        e.preventDefault();
        if (!this.submitGuard.isSubmitting()) {
          this.close();
        }
      }
    });
    const footer = contentEl.createDiv("sidenote-modal-footer");
    const cancelButton = footer.createEl("button", {
      text: "Cancel",
      cls: "sidenote-modal-cancel-btn"
    });
    this.cancelButtonEl = cancelButton;
    const submitButton = footer.createEl("button", {
      text: this.initialComment ? "Save" : "Add",
      cls: "mod-cta sidenote-modal-submit-btn"
    });
    submitButton.setAttribute("type", "button");
    this.submitButtonEl = submitButton;
    bindModalActionHandlers({
      submitButton,
      cancelButton,
      submitGuard: this.submitGuard,
      onSubmitTriggered: async () => {
        if (this.textareaEl) this.textareaEl.blur();
        await this.submitComment();
      },
      onCancelTriggered: () => this.close()
    });
    setTimeout(() => {
      input.focus();
      if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
        input.scrollIntoView({ behavior: "smooth", block: "center" });
      }
    }, 100);
    this.modalEl.addEventListener("click", (e) => {
      if (e.target === this.modalEl) this.close();
    });
    document.body.style.overflow = "hidden";
  }
  async submitComment() {
    if (!this.textareaEl) {
      new import_obsidian.Notice("Error: Comment field is empty");
      return;
    }
    if (!this.submitGuard.tryStartSubmit()) return;
    if (this.submitButtonEl) this.submitButtonEl.disabled = true;
    if (this.cancelButtonEl) this.cancelButtonEl.disabled = true;
    this.comment = this.textareaEl.value;
    try {
      await this.onSubmit(this.comment);
      this.close();
    } catch (error) {
      new import_obsidian.Notice("Error: Failed to save comment");
      console.error("Error in onSubmit:", error);
    } finally {
      this.submitGuard.finishSubmit();
      if (this.submitButtonEl) this.submitButtonEl.disabled = false;
      if (this.cancelButtonEl) this.cancelButtonEl.disabled = false;
    }
  }
  onClose() {
    this.contentEl.empty();
    this.textareaEl = null;
    this.submitButtonEl = null;
    this.cancelButtonEl = null;
    this.submitGuard.reset();
    document.body.style.overflow = "";
  }
};

// src/ConfirmDeleteModal.ts
var import_obsidian2 = require("obsidian");
var ConfirmDeleteModal = class extends import_obsidian2.Modal {
  constructor(app, onConfirm) {
    super(app);
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("sidenote-confirm-modal");
    contentEl.createEl("h2", { text: "Delete comment" });
    contentEl.createEl("p", { text: "Are you sure you want to delete this comment? This action cannot be undone." });
    const footer = contentEl.createDiv("sidenote-modal-footer");
    const cancelButton = footer.createEl("button", {
      text: "Cancel",
      cls: "sidenote-modal-cancel-btn"
    });
    cancelButton.onclick = () => this.close();
    const deleteButton = footer.createEl("button", {
      text: "Delete",
      cls: "mod-warning sidenote-modal-submit-btn"
    });
    deleteButton.onclick = () => {
      this.onConfirm();
      this.close();
    };
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/SideNoteView.ts
var SideNoteView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin, file = null) {
    super(leaf);
    this.file = null;
    this.activeCommentId = null;
    this.showAllNotes = false;
    this.searchQuery = "";
    this.plugin = plugin;
    this.file = file;
  }
  getViewType() {
    return "sidenote-view";
  }
  getDisplayText() {
    return "Side Note";
  }
  getIcon() {
    return "message-square";
  }
  async onOpen() {
    if (!this.file) {
      this.file = this.app.workspace.getActiveFile();
    }
    this.registerDomEvent(document, "click", () => {
      this.containerEl.querySelectorAll(".sidenote-action-menu.visible").forEach((m) => m.classList.remove("visible"));
    });
    this.renderComments();
  }
  async setState(state, result) {
    if (state.filePath) {
      const file = this.app.vault.getAbstractFileByPath(state.filePath);
      if (file instanceof import_obsidian3.TFile) {
        this.file = file;
        this.renderComments();
      }
    }
    await super.setState(state, result);
  }
  updateActiveFile(file) {
    this.file = file;
    this.renderComments();
  }
  highlightComment(commentId) {
    this.activeCommentId = commentId;
    this.renderComments();
    setTimeout(() => {
      const commentEl = this.containerEl.querySelector(`[data-comment-id="${commentId}"]`);
      if (commentEl) {
        commentEl.scrollIntoView({ behavior: "smooth", block: "center" });
      }
    }, 100);
  }
  setShowAllNotes(value) {
    this.showAllNotes = value;
    this.renderComments();
  }
  renderCommentItem(container, comment) {
    const commentEl = container.createDiv("sidenote-comment-item");
    commentEl.setAttribute("data-comment-id", comment.id);
    if (comment.resolved) commentEl.addClass("resolved");
    if (this.activeCommentId === comment.id) commentEl.addClass("active");
    const headerEl = commentEl.createDiv("sidenote-comment-header");
    const textInfoEl = headerEl.createDiv("sidenote-comment-text-info");
    textInfoEl.createEl("h4", { text: comment.selectedText, cls: "sidenote-selected-text" });
    textInfoEl.createEl("small", { text: new Date(comment.timestamp).toLocaleString(), cls: "sidenote-timestamp" });
    const actionsEl = headerEl.createDiv("sidenote-comment-actions");
    commentEl.addEventListener("click", async (event) => {
      var _a;
      if ((_a = event.target) == null ? void 0 : _a.closest("a")) return;
      if (event.detail > 1) return;
      let targetLeaf = null;
      this.app.workspace.iterateAllLeaves((leaf) => {
        var _a2;
        if (leaf.view instanceof import_obsidian3.MarkdownView && ((_a2 = leaf.view.file) == null ? void 0 : _a2.path) === comment.filePath) {
          targetLeaf = leaf;
          return false;
        }
      });
      if (!targetLeaf) {
        const file = this.app.vault.getAbstractFileByPath(comment.filePath);
        if (file instanceof import_obsidian3.TFile) {
          const newLeaf = this.app.workspace.getLeaf(true);
          await newLeaf.openFile(file);
          targetLeaf = newLeaf;
        }
      }
      if (targetLeaf && targetLeaf.view instanceof import_obsidian3.MarkdownView) {
        this.app.workspace.setActiveLeaf(targetLeaf, { focus: true });
        const editor = targetLeaf.view.editor;
        editor.setSelection(
          { line: comment.startLine, ch: comment.startChar },
          { line: comment.endLine, ch: comment.endChar }
        );
        editor.scrollIntoView(
          { from: { line: comment.startLine, ch: 0 }, to: { line: comment.endLine, ch: 0 } },
          true
        );
        editor.focus();
      } else {
        new import_obsidian3.Notice("Failed to jump to Markdown view.");
      }
    });
    commentEl.addEventListener("dblclick", (event) => {
      var _a;
      if ((_a = event.target) == null ? void 0 : _a.closest("a")) return;
      event.stopPropagation();
      new CommentModal(this.app, async (editedComment) => {
        await this.plugin.editComment(comment.id, editedComment);
      }, comment.comment).open();
    });
    const contentWrapper = commentEl.createDiv({ cls: "sidenote-comment-content" });
    import_obsidian3.MarkdownRenderer.renderMarkdown(comment.comment || "", contentWrapper, comment.filePath, this);
    contentWrapper.addEventListener("click", (e) => {
      const linkEl = e.target.closest("a");
      if (!linkEl) return;
      e.preventDefault();
      e.stopPropagation();
      const href = linkEl.getAttribute("data-href") || linkEl.getAttribute("href") || "";
      if (href) this.app.workspace.openLinkText(href, comment.filePath, false);
    });
    const menuButton = actionsEl.createEl("button", { text: "...", cls: "sidenote-menu-button" });
    const menuContainer = actionsEl.createDiv("sidenote-action-menu");
    const editOption = menuContainer.createEl("button", { text: "Edit", cls: "sidenote-menu-option sidenote-menu-edit" });
    editOption.onclick = (e) => {
      e.stopPropagation();
      menuContainer.classList.remove("visible");
      new CommentModal(this.app, async (editedComment) => {
        await this.plugin.editComment(comment.id, editedComment);
      }, comment.comment).open();
    };
    const deleteOption = menuContainer.createEl("button", { text: "Delete", cls: "sidenote-menu-option sidenote-menu-delete" });
    deleteOption.onclick = (e) => {
      e.stopPropagation();
      menuContainer.classList.remove("visible");
      new ConfirmDeleteModal(this.app, () => this.plugin.deleteComment(comment.id)).open();
    };
    const resolveOption = menuContainer.createEl("button", {
      text: comment.resolved ? "Reopen" : "Resolve",
      cls: "sidenote-menu-option sidenote-menu-resolve"
    });
    resolveOption.onclick = (e) => {
      e.stopPropagation();
      menuContainer.classList.remove("visible");
      if (comment.resolved) {
        this.plugin.unresolveComment(comment.id);
      } else {
        this.plugin.resolveComment(comment.id);
      }
    };
    menuButton.onclick = (e) => {
      e.stopPropagation();
      menuContainer.classList.toggle("visible");
    };
  }
  renderComments() {
    this.containerEl.empty();
    this.containerEl.addClass("sidenote-view-container");
    const viewHeader = this.containerEl.createDiv("sidenote-view-header");
    const toggleBtn = viewHeader.createEl("button", {
      text: this.showAllNotes ? "Current File" : "All Notes",
      cls: "sidenote-view-toggle"
    });
    toggleBtn.onclick = () => {
      this.showAllNotes = !this.showAllNotes;
      this.renderComments();
    };
    const searchInput = viewHeader.createEl("input", {
      cls: "sidenote-search-input",
      attr: { type: "text", placeholder: "Search comments..." }
    });
    searchInput.value = this.searchQuery;
    const applySearch = () => {
      this.searchQuery = searchInput.value;
      this.renderComments();
      const newInput = this.containerEl.querySelector(".sidenote-search-input");
      if (newInput) {
        newInput.focus();
        newInput.setSelectionRange(newInput.value.length, newInput.value.length);
      }
    };
    let composing = false;
    searchInput.addEventListener("compositionstart", () => {
      composing = true;
    });
    searchInput.addEventListener("compositionend", () => {
      composing = false;
      applySearch();
    });
    searchInput.addEventListener("input", () => {
      if (!composing) applySearch();
    });
    if (this.showAllNotes) {
      this.renderAllNotesView();
      return;
    }
    if (this.file) {
      let commentsForFile = this.plugin.commentManager.getCommentsForFile(this.file.path);
      if (!this.plugin.settings.showResolvedComments) {
        commentsForFile = commentsForFile.filter((c) => !c.resolved);
      }
      if (this.searchQuery.trim()) {
        const q = this.searchQuery.toLowerCase();
        commentsForFile = commentsForFile.filter(
          (c) => c.comment.toLowerCase().includes(q) || c.selectedText.toLowerCase().includes(q)
        );
      }
      if (this.plugin.settings.commentSortOrder === "position") {
        commentsForFile.sort(
          (a, b) => a.startLine !== b.startLine ? a.startLine - b.startLine : a.startChar - b.startChar
        );
      } else {
        commentsForFile.sort((a, b) => a.timestamp - b.timestamp);
      }
      if (commentsForFile.length > 0) {
        const commentsContainer = this.containerEl.createDiv("sidenote-comments-container");
        commentsForFile.forEach((comment) => this.renderCommentItem(commentsContainer, comment));
      } else {
        const emptyStateEl = this.containerEl.createDiv("sidenote-empty-state");
        if (this.searchQuery.trim()) {
          emptyStateEl.createEl("p", { text: "No comments match your search." });
        } else {
          emptyStateEl.createEl("p", { text: "No comments for this file yet." });
          emptyStateEl.createEl("p", { text: "Select text in your note and use the 'add comment to selection' command to get started." });
        }
      }
    } else {
      const emptyStateEl = this.containerEl.createDiv("sidenote-empty-state");
      emptyStateEl.createEl("p", { text: "No file selected." });
      emptyStateEl.createEl("p", { text: "Open a file to see its comments." });
    }
  }
  renderAllNotesView() {
    var _a, _b;
    let allComments = this.plugin.commentManager.getComments();
    if (!this.plugin.settings.showResolvedComments) {
      allComments = allComments.filter((c) => !c.resolved);
    }
    if (this.searchQuery.trim()) {
      const q = this.searchQuery.toLowerCase();
      allComments = allComments.filter(
        (c) => c.comment.toLowerCase().includes(q) || c.selectedText.toLowerCase().includes(q)
      );
    }
    if (allComments.length === 0) {
      const emptyStateEl = this.containerEl.createDiv("sidenote-empty-state");
      emptyStateEl.createEl("p", {
        text: this.searchQuery.trim() ? "No comments match your search." : "No comments found across all notes."
      });
      return;
    }
    const byFile = /* @__PURE__ */ new Map();
    for (const comment of allComments) {
      const group = (_a = byFile.get(comment.filePath)) != null ? _a : [];
      group.push(comment);
      byFile.set(comment.filePath, group);
    }
    const commentsContainer = this.containerEl.createDiv("sidenote-comments-container");
    for (const [filePath, comments] of byFile) {
      const fileName = (_b = filePath.split("/").pop()) != null ? _b : filePath;
      const fileSection = commentsContainer.createDiv("sidenote-file-section");
      fileSection.createEl("h3", { text: fileName, cls: "sidenote-file-heading" });
      const sorted = [...comments];
      if (this.plugin.settings.commentSortOrder === "position") {
        sorted.sort((a, b) => a.startLine !== b.startLine ? a.startLine - b.startLine : a.startChar - b.startChar);
      } else {
        sorted.sort((a, b) => a.timestamp - b.timestamp);
      }
      for (const comment of sorted) {
        this.renderCommentItem(fileSection, comment);
      }
    }
  }
  getState() {
    var _a, _b;
    return { filePath: (_b = (_a = this.file) == null ? void 0 : _a.path) != null ? _b : null };
  }
  onunload() {
  }
};

// src/SideNoteSettingTab.ts
var import_obsidian4 = require("obsidian");
var SideNoteSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Comment sort order").setDesc("Choose how comments are sorted in the custom view.").addDropdown(
      (dropdown) => dropdown.addOption("timestamp", "By timestamp").addOption("position", "By position in file").setValue(this.plugin.settings.commentSortOrder).onChange(async (value) => {
        this.plugin.settings.commentSortOrder = value;
        await this.plugin.saveData();
        this.rerenderViews();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show highlights in editor").setDesc("Display highlights for commented text in the editor. After changing this setting, please restart Obsidian to see the effect.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showHighlights).onChange(async (value) => {
        this.plugin.settings.showHighlights = value;
        await this.plugin.saveData();
        this.plugin.refreshEditorDecorations();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show resolved comments").setDesc("Display resolved comments in the sidebar (shown dimmed). Uncheck to hide resolved comments entirely.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showResolvedComments).onChange(async (value) => {
        this.plugin.settings.showResolvedComments = value;
        await this.plugin.saveData();
        this.rerenderViews();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Highlight color").setDesc("Choose the color for highlighted comments in the editor").addColorPicker(
      (colorPicker) => colorPicker.setValue(this.plugin.settings.highlightColor || "#FFC800").onChange(async (value) => {
        this.plugin.settings.highlightColor = value;
        await this.plugin.saveData();
        this.plugin.applyHighlightColor();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Highlight opacity").setDesc("Set the transparency of the highlight (0 = transparent, 1 = opaque)").addSlider(
      (slider) => slider.setLimits(0, 1, 0.1).setValue(this.plugin.settings.highlightOpacity || 0.2).onChange(async (value) => {
        this.plugin.settings.highlightOpacity = value;
        await this.plugin.saveData();
        this.plugin.applyHighlightColor();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Markdown comments folder").setDesc("Folder (relative to vault) where sidenote markdown backup files are stored").addText(
      (text) => text.setPlaceholder("side-note-comments").setValue(this.plugin.settings.markdownFolder || "").onChange(async (value) => {
        this.plugin.settings.markdownFolder = value.trim() || "side-note-comments";
        await this.plugin.saveData();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Create Markdown Backup").setDesc("Export all comments to markdown files in the configured folder").addButton(
      (button) => button.setButtonText("Create Backup").onClick(async () => {
        await this.plugin.migrateInlineCommentsToMarkdown();
        new import_obsidian4.Notice("Markdown backup created successfully!");
      })
    );
    const orphanedCount = this.plugin.commentManager.getOrphanedCommentCount();
    new import_obsidian4.Setting(containerEl).setName("Orphaned comments").setDesc(`There are ${orphanedCount} orphaned comment(s). These are comments whose original text was deleted.`);
    new import_obsidian4.Setting(containerEl).addButton(
      (button) => button.setButtonText(`Delete ${orphanedCount} orphaned comment(s)`).setWarning().onClick(async () => {
        const deleted = this.plugin.commentManager.deleteOrphanedComments();
        await this.plugin.saveData();
        this.rerenderViews();
        new import_obsidian4.Notice(`Deleted ${deleted} orphaned comment(s)!`);
        this.display();
      }).setDisabled(orphanedCount === 0)
    );
  }
  rerenderViews() {
    this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
      if (leaf.view instanceof SideNoteView) {
        leaf.view.renderComments();
      }
    });
  }
};

// src/highlightPlugin.ts
var import_obsidian5 = require("obsidian");
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var forceUpdateEffect = import_state.StateEffect.define();
function createHighlightPlugin(plugin) {
  return import_view.ViewPlugin.fromClass(class {
    constructor(view) {
      this.positions = /* @__PURE__ */ new Map();
      this.filePath = null;
      this.view = view;
      this.boundHandleClick = this.handleClick.bind(this);
      this.view.dom.addEventListener("click", this.boundHandleClick);
      this.filePath = this.resolveFilePath(view);
      this.initPositions(view);
      this.decorations = this.buildDecorations(view);
    }
    destroy() {
      this.view.dom.removeEventListener("click", this.boundHandleClick);
    }
    handleClick(event) {
      const highlight = event.target.closest(".sidenote-highlight");
      if (!highlight) return;
      const commentId = highlight.getAttribute("data-comment-id");
      if (commentId) plugin.activateViewAndHighlightComment(commentId);
    }
    resolveFilePath(view) {
      let filePath = null;
      plugin.app.workspace.iterateAllLeaves((leaf) => {
        if (leaf.view instanceof import_obsidian5.MarkdownView && leaf.view.file) {
          const cm = leaf.view.editor.cm;
          if (cm === view) filePath = leaf.view.file.path;
        }
      });
      return filePath;
    }
    initPositions(view) {
      this.positions = /* @__PURE__ */ new Map();
      if (!this.filePath || !plugin.settings.showHighlights) return;
      const doc = view.state.doc;
      for (const comment of plugin.commentManager.getCommentsForFile(this.filePath)) {
        if (comment.resolved || comment.isOrphaned) continue;
        try {
          const sl = doc.line(comment.startLine + 1);
          const from = sl.from + comment.startChar;
          const el = doc.line(comment.endLine + 1);
          const to = el.from + comment.endChar;
          if (from >= 0 && to <= doc.length && from < to) {
            const textAtCoords = doc.sliceString(from, to);
            if (textAtCoords === comment.selectedText) {
              this.positions.set(comment.id, { from, to, selectedText: comment.selectedText });
            }
          }
        } catch (e) {
        }
      }
    }
    update(update) {
      const hasForceUpdate = update.transactions.some(
        (tr) => tr.effects.some((e) => e.is(forceUpdateEffect))
      );
      if (hasForceUpdate) {
        this.filePath = this.resolveFilePath(update.view);
        this.initPositions(update.view);
      } else if (update.docChanged) {
        const newPositions = /* @__PURE__ */ new Map();
        const doc = update.view.state.doc;
        for (const [id, { from, to, selectedText }] of this.positions) {
          const newFrom = update.changes.mapPos(from, -1);
          const newTo = update.changes.mapPos(to, 1);
          if (newFrom < newTo) {
            const currentText = doc.sliceString(newFrom, newTo);
            if (currentText === selectedText) {
              newPositions.set(id, { from: newFrom, to: newTo, selectedText });
              const comment = plugin.commentManager.getComments().find((c) => c.id === id);
              if (comment) {
                const sl = doc.lineAt(newFrom);
                const el = doc.lineAt(newTo);
                comment.startLine = sl.number - 1;
                comment.startChar = newFrom - sl.from;
                comment.endLine = el.number - 1;
                comment.endChar = newTo - el.from;
              }
            } else {
              const comment = plugin.commentManager.getComments().find((c) => c.id === id);
              if (comment) comment.isOrphaned = true;
            }
          } else {
            const comment = plugin.commentManager.getComments().find((c) => c.id === id);
            if (comment) comment.isOrphaned = true;
          }
        }
        this.positions = newPositions;
      }
      this.decorations = this.buildDecorations(update.view);
    }
    buildDecorations(view) {
      const builder = new import_state.RangeSetBuilder();
      if (!plugin.settings.showHighlights || !this.filePath) return builder.finish();
      const doc = view.state.doc;
      const decorationsArray = [];
      for (const [id, { from, to }] of this.positions) {
        if (from >= 0 && to <= doc.length && from < to) {
          decorationsArray.push({
            from,
            to,
            decoration: import_view.Decoration.mark({
              class: "sidenote-highlight",
              attributes: { "data-comment-id": id }
            })
          });
        }
      }
      for (const comment of plugin.commentManager.getCommentsForFile(this.filePath)) {
        if (comment.resolved || !comment.isOrphaned) continue;
        try {
          const line = doc.line(comment.startLine + 1);
          const from = line.from + comment.startChar;
          const to = Math.min(from + 1, line.to);
          if (from >= 0 && to <= doc.length && from < to) {
            decorationsArray.push({
              from,
              to,
              decoration: import_view.Decoration.mark({
                class: "sidenote-highlight orphaned",
                attributes: { "data-comment-id": comment.id }
              })
            });
          }
        } catch (e) {
        }
      }
      decorationsArray.sort((a, b) => a.from - b.from);
      for (const { from, to, decoration } of decorationsArray) {
        builder.add(from, to, decoration);
      }
      return builder.finish();
    }
  }, {
    decorations: (v) => v.decorations
  });
}

// src/utils.ts
var import_obsidian6 = require("obsidian");
async function generateHash(text) {
  try {
    const encoder = new TextEncoder();
    const data = encoder.encode(text);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  } catch (e) {
    try {
      const nodeCrypto = require("crypto");
      return nodeCrypto.createHash("sha256").update(text).digest("hex");
    } catch (e2) {
      new import_obsidian6.Notice("Warning: Could not generate proper hash, using fallback");
      let hash = 0;
      for (let i = 0; i < text.length; i++) {
        const char = text.charCodeAt(i);
        hash = (hash << 5) - hash + char;
        hash = hash & hash;
      }
      return Math.abs(hash).toString(16);
    }
  }
}
function generateCommentId() {
  if (typeof crypto !== "undefined" && typeof crypto.randomUUID === "function") {
    return crypto.randomUUID();
  }
  try {
    const nodeCrypto = require("crypto");
    if (typeof nodeCrypto.randomUUID === "function") {
      return nodeCrypto.randomUUID();
    }
  } catch (e) {
  }
  return `sn-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
async function switchToSideNoteView(app) {
  const activeFile = app.workspace.getActiveFile();
  if (!activeFile) {
    new import_obsidian6.Notice("No active Markdown file found.");
    return;
  }
  let leaf = null;
  try {
    leaf = app.workspace.getLeaf("split", "vertical");
  } catch (error) {
    new import_obsidian6.Notice("Failed to create a new split view for comments.");
    console.error("Error creating split leaf:", error);
    return;
  }
  if (leaf) {
    await leaf.setViewState({
      type: "sidenote-view",
      state: { filePath: activeFile.path },
      active: true
    });
    void app.workspace.revealLeaf(leaf);
  } else {
    new import_obsidian6.Notice("Failed to create or find a leaf for the comment view.");
  }
}

// src/types.ts
var DEFAULT_SETTINGS = {
  commentSortOrder: "position",
  showHighlights: true,
  markdownFolder: "side-note-comments",
  highlightColor: "#FFC800",
  highlightOpacity: 0.2,
  showResolvedComments: false
};

// src/main.ts
var SideNote = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.comments = [];
    this.editorUpdateTimers = {};
    this.duplicateAddWindowMs = 800;
    this.lastAddFingerprint = null;
  }
  registerFreshSettingTab() {
    var _a;
    const appWithSettings = this.app;
    const pluginTabs = (_a = appWithSettings.setting) == null ? void 0 : _a.pluginTabs;
    if (pluginTabs && pluginTabs[this.manifest.id]) {
      delete pluginTabs[this.manifest.id];
    }
    this.addSettingTab(new SideNoteSettingTab(this.app, this));
  }
  normalizeCommentsFolderPath(raw) {
    const trimmed = raw.trim() || DEFAULT_SETTINGS.markdownFolder;
    if (trimmed.startsWith("/") || trimmed.split("/").some((seg) => seg === "..")) {
      return null;
    }
    return trimmed.replace(/^\/+|\/+$/g, "");
  }
  async ensureCommentFolder() {
    const raw = this.settings.markdownFolder;
    const normalized = this.normalizeCommentsFolderPath(raw);
    if (!normalized) {
      new import_obsidian7.Notice("SideNote: Invalid comments folder path. Using default.");
      return DEFAULT_SETTINGS.markdownFolder;
    }
    const exists = await this.app.vault.adapter.exists(normalized);
    if (!exists) {
      await this.app.vault.createFolder(normalized);
    }
    return normalized;
  }
  getSideNoteFilePath(notePath) {
    var _a;
    const raw = this.settings.markdownFolder;
    const normalized = (_a = this.normalizeCommentsFolderPath(raw)) != null ? _a : DEFAULT_SETTINGS.markdownFolder;
    const base = notePath.replace(/\.md$/i, "").replace(/\//g, "__");
    return `${normalized}/${base}-sidenote.md`;
  }
  async writeCommentToMarkdown(notePath, excerpt, body, commentId) {
    await this.ensureCommentFolder();
    const filePath = this.getSideNoteFilePath(notePath);
    const block = buildMarkdownBlock(excerpt, body, commentId);
    const existing = this.app.vault.getAbstractFileByPath(filePath);
    if (existing instanceof import_obsidian7.TFile) {
      const content = await this.app.vault.read(existing);
      const updated = content.trim().length === 0 ? block : `${content}

${block}`;
      await this.app.vault.modify(existing, updated);
    } else {
      await this.app.vault.create(filePath, `# Side Notes for ${notePath}

${block}`);
    }
    return filePath;
  }
  async onload() {
    await this.loadPluginData();
    this.commentManager = new CommentManager(this.comments);
    await this.migrateComments();
    this.registerEditorExtension([createHighlightPlugin(this)]);
    this.registerMarkdownPreviewHighlights();
    this.registerFreshSettingTab();
    this.registerView("sidenote-view", (leaf) => new SideNoteView(leaf, this));
    this.addCommand({
      id: "open-comment-view",
      name: "Open in Split View",
      callback: () => {
        void switchToSideNoteView(this.app);
      }
    });
    this.addCommand({
      id: "activate-view",
      name: "Open in Sidebar",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "view-all-comments",
      name: "View all comments",
      icon: "list",
      callback: async () => {
        await this.activateView();
        this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
          if (leaf.view instanceof SideNoteView) leaf.view.setShowAllNotes(true);
        });
      }
    });
    this.addCommand({
      id: "add-comment-to-selection",
      name: "Add comment to selection",
      icon: "message-square",
      editorCallback: (editor, view) => {
        var _a;
        this.openAddCommentModal(editor, (_a = view.file) == null ? void 0 : _a.path);
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        if (editor.somethingSelected()) {
          menu.addItem((item) => {
            item.setTitle("Add comment to selection").setIcon("message-square").onClick(() => {
              var _a;
              return this.openAddCommentModal(editor, (_a = view.file) == null ? void 0 : _a.path);
            });
          });
        }
      })
    );
    this.addRibbonIcon("message-square", "Side Note: Open in Sidebar", () => {
      this.activateView();
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf && leaf.view instanceof import_obsidian7.MarkdownView) {
          const file = leaf.view.file;
          this.app.workspace.getLeavesOfType("sidenote-view").forEach((sideNoteLeaf) => {
            if (sideNoteLeaf.view instanceof SideNoteView) {
              sideNoteLeaf.view.updateActiveFile(file);
            }
          });
          this.refreshEditorDecorations();
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (file instanceof import_obsidian7.TFile) {
          this.commentManager.renameFile(oldPath, file.path);
          void this.saveData();
          this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
            if (leaf.view instanceof SideNoteView) leaf.view.renderComments();
          });
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", async (file) => {
        var _a;
        if (file.path === ".obsidian/plugins/side-note/data.json" || file instanceof import_obsidian7.TFile && file.name === "data.json" && ((_a = file.parent) == null ? void 0 : _a.name) === "side-note") {
          try {
            await this.loadPluginData();
            await this.migrateComments();
            this.commentManager.updateComments(this.comments);
            this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
              if (leaf.view instanceof SideNoteView) leaf.view.renderComments();
            });
          } catch (error) {
            console.error("Error reloading plugin data:", error);
          }
        } else if (file instanceof import_obsidian7.TFile && file.extension === "md") {
          try {
            const fileContent = await this.app.vault.read(file);
            this.commentManager.updateCommentCoordinatesForFile(fileContent, file.path);
            await this.saveData();
            this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
              if (leaf.view instanceof SideNoteView) leaf.view.renderComments();
            });
          } catch (error) {
            console.error("Error updating comment coordinates:", error);
          }
        }
      })
    );
  }
  async activateViewAndHighlightComment(commentId) {
    await this.activateView();
    this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
      if (leaf.view instanceof SideNoteView) leaf.view.highlightComment(commentId);
    });
  }
  async activateView() {
    const { workspace } = this.app;
    const leaves = workspace.getLeavesOfType("sidenote-view");
    let leaf = leaves.length > 0 ? leaves[0] : null;
    if (!leaf) {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({ type: "sidenote-view", active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
      if (leaf.view instanceof SideNoteView) {
        leaf.view.updateActiveFile(workspace.getActiveFile());
      }
    }
  }
  async onCommentsChanged(message) {
    await this.saveData();
    this.app.workspace.getLeavesOfType("sidenote-view").forEach((leaf) => {
      if (leaf.view instanceof SideNoteView) leaf.view.renderComments();
    });
    this.refreshEditorDecorations();
    new import_obsidian7.Notice(message);
  }
  createAddFingerprint(comment) {
    return [
      comment.filePath,
      comment.startLine,
      comment.startChar,
      comment.endLine,
      comment.endChar,
      comment.selectedText,
      comment.comment
    ].join("|");
  }
  async addComment(newComment) {
    const now = Date.now();
    const fingerprint = this.createAddFingerprint(newComment);
    if (this.lastAddFingerprint && this.lastAddFingerprint.key === fingerprint && now - this.lastAddFingerprint.at < this.duplicateAddWindowMs) {
      return;
    }
    this.lastAddFingerprint = { key: fingerprint, at: now };
    this.commentManager.addComment(newComment);
    await this.onCommentsChanged("Comment added!");
  }
  async editComment(commentId, newCommentText) {
    this.commentManager.editComment(commentId, newCommentText);
    await this.onCommentsChanged("Comment updated!");
  }
  async deleteComment(commentId) {
    this.commentManager.deleteComment(commentId);
    await this.onCommentsChanged("Comment deleted!");
  }
  async resolveComment(commentId) {
    this.commentManager.resolveComment(commentId);
    await this.onCommentsChanged("Comment resolved!");
  }
  async unresolveComment(commentId) {
    this.commentManager.unresolveComment(commentId);
    await this.onCommentsChanged("Comment reopened!");
  }
  openAddCommentModal(editor, filePath) {
    const selection = editor.getSelection();
    if (!(selection == null ? void 0 : selection.trim()) || !filePath) {
      new import_obsidian7.Notice("Please select some text to add a comment.");
      return;
    }
    const cursorStart = editor.getCursor("from");
    const cursorEnd = editor.getCursor("to");
    new CommentModal(this.app, async (commentText) => {
      const newComment = {
        id: generateCommentId(),
        filePath,
        startLine: cursorStart.line,
        startChar: cursorStart.ch,
        endLine: cursorEnd.line,
        endChar: cursorEnd.ch,
        selectedText: selection,
        selectedTextHash: await generateHash(selection),
        comment: commentText,
        timestamp: Date.now(),
        isOrphaned: false
      };
      await this.addComment(newComment);
    }).open();
  }
  async loadPluginData() {
    const loadedData = Object.assign({}, { comments: [] }, DEFAULT_SETTINGS, await this.loadData());
    this.settings = {
      commentSortOrder: loadedData.commentSortOrder || DEFAULT_SETTINGS.commentSortOrder,
      showHighlights: loadedData.showHighlights !== void 0 ? loadedData.showHighlights : DEFAULT_SETTINGS.showHighlights,
      markdownFolder: loadedData.markdownFolder || DEFAULT_SETTINGS.markdownFolder,
      highlightColor: loadedData.highlightColor || DEFAULT_SETTINGS.highlightColor,
      highlightOpacity: loadedData.highlightOpacity !== void 0 ? loadedData.highlightOpacity : DEFAULT_SETTINGS.highlightOpacity,
      showResolvedComments: loadedData.showResolvedComments !== void 0 ? loadedData.showResolvedComments : DEFAULT_SETTINGS.showResolvedComments
    };
    this.comments = loadedData.comments || [];
    this.applyHighlightColor();
  }
  async migrateComments() {
    let needsSave = false;
    for (const comment of this.comments) {
      if (!comment.id) {
        comment.id = generateCommentId();
        needsSave = true;
      }
      if (!comment.selectedTextHash && comment.selectedText) {
        comment.selectedTextHash = await generateHash(comment.selectedText);
        needsSave = true;
      }
      if (comment.isOrphaned === void 0) {
        comment.isOrphaned = false;
        needsSave = true;
      }
    }
    if (needsSave) await this.saveData();
  }
  async migrateInlineCommentsToMarkdown() {
    let changed = false;
    for (const comment of this.comments) {
      if (!comment.commentPath) {
        const path = await this.writeCommentToMarkdown(
          comment.filePath,
          comment.selectedText,
          comment.comment,
          comment.id
        );
        comment.commentPath = path;
        changed = true;
      }
    }
    if (changed) await this.saveData();
  }
  registerMarkdownPreviewHighlights() {
    this.registerMarkdownPostProcessor((element, context) => {
      if (!element.closest(".markdown-preview-view")) return;
      if (!this.settings.showHighlights) return;
      const comments = this.commentManager.getCommentsForFile(context.sourcePath).filter((c) => !c.isOrphaned && !!c.selectedText);
      if (!comments.length) return;
      const textNodes = [];
      const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
      let offset = 0;
      while (walker.nextNode()) {
        const node = walker.currentNode;
        const value = node.nodeValue || "";
        if (!value.length) continue;
        textNodes.push({ node, start: offset, end: offset + value.length });
        offset += value.length;
      }
      const fullText = textNodes.map((t) => t.node.nodeValue || "").join("");
      if (!fullText.length) return;
      const wraps = [];
      for (const comment of comments) {
        if (!comment.selectedText) continue;
        const idx = fullText.indexOf(comment.selectedText);
        if (idx !== -1) wraps.push({ start: idx, end: idx + comment.selectedText.length, comment });
      }
      if (!wraps.length) return;
      const findPos = (absolute) => {
        for (const entry of textNodes) {
          if (absolute >= entry.start && absolute <= entry.end) {
            return { node: entry.node, offsetInNode: absolute - entry.start };
          }
        }
        return null;
      };
      wraps.sort((a, b) => b.start - a.start);
      for (const wrap of wraps) {
        const startPos = findPos(wrap.start);
        const endPos = findPos(wrap.end);
        if (!startPos || !endPos) continue;
        try {
          const range = document.createRange();
          range.setStart(startPos.node, startPos.offsetInNode);
          range.setEnd(endPos.node, endPos.offsetInNode);
          const span = document.createElement("span");
          span.classList.add("sidenote-highlight", "sidenote-highlight-preview");
          span.dataset.commentId = wrap.comment.id;
          span.addEventListener("click", (event) => {
            if (event.button !== 0) return;
            void this.activateViewAndHighlightComment(wrap.comment.id);
          });
          span.addEventListener("contextmenu", () => {
          });
          range.surroundContents(span);
        } catch (e) {
          console.warn("Failed to wrap preview highlight", e);
        }
      }
    });
  }
  applyHighlightColor() {
    const root = document.documentElement;
    const { highlightColor: color, highlightOpacity: opacity } = this.settings;
    const rgb = this.hexToRgb(color);
    root.style.setProperty("--sidenote-highlight-color", `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${opacity})`);
    root.style.setProperty("--sidenote-highlight-hover", `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${Math.min(opacity + 0.15, 1)})`);
    root.style.setProperty("--sidenote-highlight-border", `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${Math.min(opacity + 0.4, 1)})`);
    root.style.setProperty("--sidenote-orphaned-color", `rgba(255, 100, 100, ${opacity})`);
    root.style.setProperty("--sidenote-orphaned-hover", `rgba(255, 100, 100, ${Math.min(opacity + 0.15, 1)})`);
    root.style.setProperty("--sidenote-orphaned-border", `rgba(255, 100, 100, ${Math.min(opacity + 0.35, 1)})`);
    this.refreshEditorDecorations();
  }
  hexToRgb(hex) {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? { r: parseInt(result[1], 16), g: parseInt(result[2], 16), b: parseInt(result[3], 16) } : { r: 255, g: 200, b: 0 };
  }
  async saveData() {
    const dataToSave = { ...this.settings, comments: this.comments };
    await super.saveData(dataToSave);
    this.refreshEditorDecorations();
  }
  refreshEditorDecorations() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view instanceof import_obsidian7.MarkdownView) {
        const cm = leaf.view.editor.cm;
        if (cm == null ? void 0 : cm.dispatch) {
          cm.dispatch({ effects: [forceUpdateEffect.of(null)] });
        }
      }
    });
  }
};


/* nosourcemap */